author:
  email: null
  name: An Author
  twitter: null
  url: null
baseurl: /tragedy-of-king-lear
collections:
  annotations:
    output: true
    permalink: /annotations/:path/
  volume_pages:
    output: true
    permalink: /pages/:path/
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    extra_js:
    - deepzoom.js
    - openseadragon.min.js
    - volume-page.js
    - hammer.min.js
    layout: volume_page
    short_label: p.
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
homepage_image: http://digital.library.wayne.edu/readux/books/wayne:fourthfolio_Readux_VirtualVolume/pages/wayne:fourthfolio_Readux_VirtualPage_1/single-page/
image_size:
  page:
    height: 1000
    width: 650
  small-thumbnail:
    height: 100
    width: 65
  thumbnail:
    height: 300
    width: 195
permalink: pretty
publication_info:
  author: null
  date: '2017'
  editors:
  - Jesse P. Karlsberg
  tei_xml: tei.xml
  title: The Tragedy of King Lear, an annotated digital edition
show_annotation_author: true
source_info:
  author: null
  date: '1685'
  pdf_url: http://digital.library.wayne.edu/readux/books/wayne:fourthfolio_Readux_VirtualVolume/pdf/
  title: The Tragedy of King Lear
  url: http://digital.library.wayne.edu/readux/books/wayne:fourthfolio_Readux_VirtualVolume/
  via_readux: true
tagline: ', an annotated digital edition'
title: The Tragedy of King Lear
url: http://jpkarlsberg.github.io
version: 0.6
